# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/hireza/Documents/Code/Github/HiRezaGram/ui/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(802, 600)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 40, 391, 41))
        self.label.setStyleSheet("font: 18pt \"Sans Serif\";")
        self.label.setObjectName("label")
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 80, 731, 491))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(70, 20, 721, 521))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.listView = QtWidgets.QListView(self.frame)
        self.listView.setGeometry(QtCore.QRect(0, 0, 181, 521))
        self.listView.setObjectName("listView")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(180, 480, 541, 41))
        self.textEdit.setObjectName("textEdit")
        self.btn_back = QtWidgets.QPushButton(self.frame)
        self.btn_back.setGeometry(QtCore.QRect(580, 450, 80, 23))
        self.btn_back.setObjectName("btn_back")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.page_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 70, 441, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_chat_list = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_chat_list.setObjectName("btn_chat_list")
        self.verticalLayout.addWidget(self.btn_chat_list)
        self.btn_contacts_list = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_contacts_list.setObjectName("btn_contacts_list")
        self.verticalLayout.addWidget(self.btn_contacts_list)
        self.btn_groups = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_groups.setObjectName("btn_groups")
        self.verticalLayout.addWidget(self.btn_groups)
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Welcome to HiReza Chat Server"))
        self.btn_back.setText(_translate("Dialog", "Back"))
        self.btn_chat_list.setText(_translate("Dialog", "Chat list"))
        self.btn_contacts_list.setText(_translate("Dialog", "Contacts list"))
        self.btn_groups.setText(_translate("Dialog", "Groups"))
